dataset:
  name: PDE_KS
  pair_id: 2
model:
  name: FNO
  # FNO-specific parameters
  modes1: 23
  modes2: 11
  width: 102
  in_channels: 1
  out_channels: 1
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 0.0005187666816872868
  epochs: 500
  batch_size: 128
  activation: "gelu"
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
