dataset:
  name: PDE_KS
  pair_id: '1-6'  # Run on sub-datasets 1 through 6

model:
  name: FNO
  # FNO-specific parameters
  modes1: 12  # Number of Fourier modes in first dimension
  modes2: 12  # Number of Fourier modes in second dimension
  width: 20   # Width of the network
  in_channels: 1  # Number of input channels
  out_channels: 1  # Number of output channels
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 1e-3
  epochs: 500
  batch_size: 32
  activation: "gelu"  # Default activation function
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5 