dataset:
  name: ODE_Lorenz
  pair_id: 9
model:
  name: FNO
  modes1: 21
  modes2: 10
  width: 108
  in_channels: 1
  out_channels: 1
  optimizer: "adam"
  learning_rate: 0.000640362318928464
  epochs: 500
  batch_size: 64
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8