dataset:
  name: PDE_KS
  pair_id: 7
model:
  name: FNO
  # FNO-specific parameters
  modes1: 12
  modes2: 10
  width: 68
  in_channels: 1
  out_channels: 1
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 0.00012166824099428697
  epochs: 500
  batch_size: 128
  activation: "gelu"
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
