dataset:
  name: ODE_Lorenz
  pair_id: 1

model:
  name: FNO
  modes1: 9
  modes2: 29
  width: 119
  in_channels: 1
  out_channels: 1

  optimizer: "adam"
  learning_rate: 0.0018941966971199049
  epochs: 500
  batch_size: 128

  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
