dataset:
  name: PDE_KS
  pair_id: 1
model:
  name: FNO
  # FNO-specific parameters
  modes1: 14
  modes2: 15
  width: 89
  in_channels: 1
  out_channels: 1
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 0.00018276087931484
  epochs: 500
  batch_size: 128
  activation: "gelu"
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
