dataset:
  name: PDE_KS
  pair_id: 5
model:
  name: FNO
  # FNO-specific parameters
  modes1: 24
  modes2: 25
  width: 64
  in_channels: 1
  out_channels: 1
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 0.0001651955084138396
  epochs: 500
  batch_size: 16
  activation: "gelu"
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
