dataset:
  name: PDE_KS
  pair_id: 9
model:
  name: FNO
  # FNO-specific parameters
  modes1: 9
  modes2: 16
  width: 58
  in_channels: 1
  out_channels: 1
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 0.004430058424048679
  epochs: 500
  batch_size: 16
  activation: "gelu"
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
