dataset:
  name: PDE_KS
  pair_id: 3
model:
  name: FNO
  # FNO-specific parameters
  modes1: 25
  modes2: 29
  width: 100
  in_channels: 1
  out_channels: 1
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 0.0001023782764148715
  epochs: 500
  batch_size: 32
  activation: "gelu"
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
