dataset:
  name: PDE_KS
  pair_id: 6
model:
  name: FNO
  # FNO-specific parameters
  modes1: 16
  modes2: 27
  width: 101
  in_channels: 1
  out_channels: 1
  
  # Training parameters
  optimizer: "adam"
  learning_rate: 0.0021431637591815445
  epochs: 500
  batch_size: 64
  activation: "gelu"
  
  # Learning rate scheduler
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
