dataset:
  name: ODE_Lorenz
  pair_id: 2
model:
  name: FNO
  modes1: 8
  modes2: 23
  width: 47
  in_channels: 1
  out_channels: 1

  optimizer: "adam"
  learning_rate: 0.008886335226602479
  epochs: 500
  batch_size: 32

  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  train_ratio: 0.8
