dataset:
  name: ODE_Lorenz
  pair_id: 7
model:
  name: FNO
  modes1: 8
  modes2: 24
  width: 115
  in_channels: 1
  out_channels: 1
  optimizer: "adam"
  learning_rate: 0.0035101808644851028
  epochs: 500
  batch_size: 32
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8
