dataset:
  name: ODE_Lorenz
  pair_id: 5
model:
  name: FNO
  modes1: 17
  modes2: 19
  width: 90
  in_channels: 1
  out_channels: 1
  optimizer: "adam"
  learning_rate: 0.0012754175685967479
  epochs: 500
  batch_size: 128
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8