dataset:
  name: ODE_Lorenz
  pair_id: 3
model:
  name: FNO
  modes1: 25
  modes2: 26
  width: 85
  in_channels: 1
  out_channels: 1
  optimizer: "adam"
  learning_rate: 0.0002627857451436251
  epochs: 500
  batch_size: 64
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8