dataset:
  name: ODE_Lorenz
  pair_id: 6
model:
  name: FNO
  modes1: 27
  modes2: 16
  width: 61
  in_channels: 1
  out_channels: 1
  optimizer: "adam"
  learning_rate: 0.00017263745865202837
  epochs: 500
  batch_size: 32
  scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.5
  
  train_ratio: 0.8

